// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsHqD8LNqi3hd08_ESvLMdgRVYHaEA2G8',
    appId: '1:398918307760:android:b594661c43a253d93d9075',
    messagingSenderId: '398918307760',
    projectId: 'whatsapp-clone-flutter-71990',
    storageBucket: 'whatsapp-clone-flutter-71990.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgii6Gz2mbYcpjBUtsB_Mz_lc1fklo9VU',
    appId: '1:398918307760:ios:00696766ea46cd5d3d9075',
    messagingSenderId: '398918307760',
    projectId: 'whatsapp-clone-flutter-71990',
    storageBucket: 'whatsapp-clone-flutter-71990.appspot.com',
    iosClientId: '398918307760-b0dp5m34p92tpn0fdnr8qf2t00iq66eg.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
